export const GET_PLAYER_REQUEST = "GET_PLAYER_REQUEST";
export const GET_PLAYER_SUCCESS = "GET_PLAYER_SUCCESS";
export const GET_PLAYER_FAILED = "GET_PLAYER_FAILED";

export const ADD_PLAYER_REQUEST = "ADD_PLAYER_REQUEST";
export const ADD_PLAYER_SUCCESS = "ADD_PLAYER_SUCCESS";
export const ADD_PLAYER_FAILED = "ADD_PLAYER_FAILED";

export const EDIT_PLAYER_REQUEST = "EDIT_PLAYER_REQUEST";
export const EDIT_PLAYER_SUCCESS = "EDIT_PLAYER_SUCCESS";
export const EDIT_PLAYER_FAILED = "EDIT_PLAYER_FAILED";

export const DELETE_PLAYER_REQUEST = "DELETE_PLAYER_REQUEST";
export const DELETE_PLAYER_SUCCESS = "DELETE_PLAYER_SUCCESS";
export const DELETE_PLAYER_FAILED = "DELETE_PLAYER_FAILED";